# Generated by Django 5.1.3 on 2024-11-17 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='nombre_1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='nombre_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='nombre_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='contacto_1',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido.', regex='^\\+?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='contacto_2',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido.', regex='^\\+?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='contacto_3',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido.', regex='^\\+?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='numero',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
