# Generated by Django 5.1.3 on 2024-11-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_propiedad_nombre_1_propiedad_nombre_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parqueadero',
            name='contacto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='nombre_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
