# Generated by Django 5.1.3 on 2024-11-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_parqueadero_contacto_alter_propiedad_nombre_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parqueadero',
            name='contacto',
            field=models.CharField(max_length=20),
        ),
    ]
