# Generated by Django 5.1.3 on 2024-12-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_alter_parqueadero_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parqueadero',
            name='contacto',
            field=models.CharField(max_length=254),
        ),
    ]
