# Generated by Django 5.1.3 on 2024-12-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_alter_parqueadero_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parqueadero',
            name='contacto',
            field=models.CharField(default='No disponible', max_length=254),
        ),
    ]
