# Generated by Django 5.1.3 on 2024-12-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_alter_parqueadero_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='parqueadero',
            name='casa',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
