# Generated by Django 5.1.3 on 2024-12-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_parqueadero_casa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parqueadero',
            name='placa_vehiculo',
            field=models.CharField(max_length=6),
        ),
    ]
